@echo off
cd /d D:\Desktop
rd 我是补丁你来打我啊..\
rd 略略略……..\
rd 来呀来呀..\
rd 哈哈，你删不掉我..\
rd 傻了吧傻了吧傻了吧..\
rd 呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵..\
rd hehehe..\
rd hehehehe..\
rd 呵呵呵呵呵..\
rd 哇佛in我去奋斗I我飞我不VIU分..\
rd 千万覅U去帮我id你系修武器拿粉笔UwvIU型吧..\
rd qdvqwibciuwqbunxziswqnmfd..\
rd iqbfciuqsdiqbdiqnwjxzoiwqd..\
rd haha..\
rd ppppp..\
rd eahearh..\
rd 哈哈哈..\
rd 哈哈哈哈..\
rd 啊啊啊啊啊啊..\
rd lalalalalala..\
rd 你的电脑已中毒！！..\
rd 你的360已被卸载！..\
rd 你的腾讯杀毒已被卸载！..\
rd 你的Windows-defender已被关闭！..\
rd 你的控制面板已被损坏！..\
rd cmd已被删除！..\
rd system32文件夹已被粉碎！..\
rd 资源管理器已被关闭！..\
rd D盘已被格式化！..\
rd E盘已被销毁！..\
rd F盘已被扔出窗外！..\
rd 正在执行命令：“rd C:”！..\
rd C盘已被格式化！..\
rd 正在下载冲击波病毒！..\
rd 正在下载彩虹猫memz病毒！..\
rd 正在下载熊猫烧香病毒！..\
rd 正在下载滑稽病毒！..\
rd 正在下载CIH病毒！..\
rd 正在下载msblast病毒！..\
rd 正在同时运行所有病毒！..\
rd 你的电脑已报废..\
rd 晒萨芬比萨比滴撒..\
rd akbfiusabdosanhidonaod..\
rd aidbasiubdisabdiuandiani..\
rd aidiusadinciuqwbiqbwciudhqid..\
rd qwduqoidqnwoidnqodnwq0xjodwq..\
rd qidwwqidnbwq9ns0wqxs..\
rd qwiduqwibiwqbdxiuwqinjfiowqjdoq..\
rd qiudwwuinxoiqnwodxjwqoxjqwoizjixesax..\
rd iuefiuwabfiuaidhq..\
rd oawdbiqodnboiadna..\
rd uvdabdiuqwiqnbdxoias..\
rd aidbqiwbdiwqnxoiwax..\
rd aidbwaiudnawinxa..\
rd a..\
rd b..\
rd c..\
rd d..\
rd e..\
rd f..\
rd g..\
rd h..\
rd i..\
rd j..\
rd k..\
rd l..\
rd m..\
rd n..\
rd o..\
rd p..\
rd q..\
rd r..\
rd s..\
rd t..\
rd u..\
rd v..\
rd w..\
rd x..\
rd y..\
rd z..\
md 哈哈..